import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Aside, Header } from './components'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

      <Header/>
      
      <Aside/>

      <div className="p-4 sm:ml-64">
        {children}
      </div>

        
      </body>
    </html>
  )
}
